import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {emi,schedule,eirSchedule,periodicIRR,allocate,split,clockRemaining,pauseClock,resumeClock,classifyAttempt,round} from '../src/engine.mjs';import {fresh,read,save,validate,KEY,recoverReset} from '../src/store.mjs';import {check} from '../scripts/check-content.mjs';
const bank=JSON.parse(fs.readFileSync(new URL('../content/curriculum.json',import.meta.url)));
function memory(raw=null){const data=new Map(raw===null?[]:[[KEY,raw]]);return {data,getItem:key=>data.get(key)??null,setItem:(key,val)=>data.set(key,val)};}
test('Authored curriculum schema, source coverage and all worked numeric identities',()=>assert.match(check(),/159 MCQs \/ 15 cases/));
test('Positive-rate EMI schedule independently conserves all principal and final rounding',()=>{assert(Math.abs(emi(120000,12,12)-10661.8546414)<1e-6);const s=schedule(120000,12,12);assert.equal(s[1].closing,100981.68);assert.equal(s.at(-1).payment,10661.91);assert.equal(s.at(-1).closing,0);assert.equal(round(s.reduce((n,r)=>n+r.principal,0)),120000);assert.equal(round(s.reduce((n,r)=>n+r.interest,0)),7942.26);assert.equal(emi(120000,0,12),10000);});
test('EIR positive fee schedule reconciles gross, contra-asset and carrying every period',()=>{const x=eirSchedule(120000,12,12,2400);assert(Math.abs(x.yieldRate-.013212102211607513)<1e-12);const npv=-117600+x.rows.reduce((n,r,i)=>n+r.payment/(1+x.yieldRate)**(i+1),0);assert(Math.abs(npv)<1e-6);for(const r of x.rows){assert.equal(round(r.closing-r.deferred),r.carryingClose);assert.equal(round(r.interest+r.feeAccretion),r.income);}assert.equal(round(x.rows.reduce((n,r)=>n+r.income,0)),10342.26);assert.equal(x.rows.at(-1).deferred,0);assert.equal(x.rows.at(-1).carryingClose,0);assert.throws(()=>eirSchedule(1000,12,12,1000));});
test('PV/IRR conventional equal-year stream and monthly compounding',()=>{assert(Math.abs(periodicIRR(99474.08,[40000,40000,40000])-.1)<1e-8);assert(Math.abs((1.01**12-1)*100-12.6825030132)<1e-8);assert.throws(()=>periodicIRR(100,[-10,120]));});
test('Both waterfalls conserve money and expose distinct oldest unpaid principal',()=>{const buckets=[{charge:100,interest:900,principal:3000},{charge:100,interest:800,principal:3000}];for(const mode of ['vertical','horizontal']){for(const p of [0,0.01,100,4000,7900,8000]){const r=allocate(p,buckets,mode);assert.equal(round(r.applied+r.unapplied),p);assert(r.remaining.every(b=>Object.values(b).every(n=>n>=0)));assert.equal(round(r.remaining.reduce((n,b)=>n+b.charge+b.interest+b.principal,0)),round(7900-r.applied));}}assert.equal(allocate(4000,buckets).remaining[0].principal,0);assert.equal(allocate(4000,buckets,'horizontal').remaining[0].principal,900);});
test('Co-lending distinguishes interest and principal ratios and paise residual',()=>{const s=split(4000,1000,100000,.8,10.5,18);assert.equal(s.totalA,3900);assert.equal(s.totalB,1100);assert.equal(s.blended,12);const penny=split(100.01,0,100000,.8,0,0);assert.equal(round(penny.principalA+penny.principalB),100.01);});
test('Reload preserves running deadline and explicit pause preserves only remaining budget',()=>{let s={mode:'session',status:'active',deadline:61000,remaining:60000,budget:60000,paused:false};assert.equal(clockRemaining(JSON.parse(JSON.stringify(s)),11000),50000);s=pauseClock(s,21000);assert.equal(s.remaining,40000);assert.equal(clockRemaining(s,999999),40000);s=resumeClock(s,101000);assert.equal(s.deadline,141000);assert.equal(clockRemaining(s,111000),30000);assert.equal(clockRemaining(s,141000),0);assert.equal(pauseClock(s,142000).paused,false);});
test('Helped, exposed, timeout and repeat attempts cannot inflate independent-first success',()=>{let history={};let h=classifyAttempt(history,'x',{helped:true,correct:true});assert.equal(h.first.kind,'helped');history.x=h;h=classifyAttempt(history,'x',{correct:true});assert.equal(h.attempts.at(-1).kind,'repeat');assert.equal(h.first.kind,'helped');assert.equal(classifyAttempt({},'y',{correct:true,timeout:true}).first.correct,false);assert.equal(classifyAttempt({},'z',{exposed:true,correct:true}).first.kind,'helped');});
test('Corrupt and future bytes survive reads; explicit reset creates recoverable backup',()=>{for(const raw of ['{broken','{"version":99,"valuable":"future"}',JSON.stringify({...fresh(),exposed:['unknown']})]){const storage=memory(raw);const r=read(storage,bank);assert.equal(r.blocked,true);assert.equal(storage.getItem(KEY),raw);const reset=recoverReset(storage,raw);assert.equal(reset.ok,true);assert([...storage.data.entries()].some(([k,v])=>k.startsWith(KEY+':backup:')&&v===raw));}});
test('Normal and resumed assessment data validates; impossible timer and result structures do not',()=>{const x=fresh(),now=Date.now();x.session={ids:['q-math-01'],index:0,mode:'question',budget:60000,remaining:60000,deadline:now+60000,paused:false,status:'active',selected:1,helped:false,results:{},startedAt:now,lastObserved:now};assert.equal(validate(JSON.stringify(x),bank).ok,true);x.session.remaining=60001;assert.equal(validate(JSON.stringify(x),bank).ok,false);x.session.remaining=60000;x.session.deadline=null;assert.equal(validate(JSON.stringify(x),bank).ok,false);});
test('Storage unavailable and quota failure are explicit and do not replace existing bytes',()=>{const storage={getItem(){throw Error('disabled');},setItem(){throw Error('disabled');}};assert(read(storage,bank).blocked);assert.equal(save(storage,fresh()).ok,false);const m=memory('original');m.setItem=()=>{throw Error('quota');};assert.equal(recoverReset(m,'original').ok,false);assert.equal(m.getItem(KEY),'original');});
