import {money,round,schedule,allocate,split,clockRemaining,pauseClock,resumeClock,classifyAttempt} from './engine.mjs';
import {KEY,fresh,read,save,validate,recoverReset} from './store.mjs';
const main=document.querySelector('main'),notice=document.querySelector('#notice');
let bank;try{const response=await fetch(new URL('../content/curriculum.json',import.meta.url));if(!response.ok)throw Error('Content unavailable');bank=await response.json();}catch{main.innerHTML='<h1>Learning content could not load</h1><p>Reconnect and reload. Offline reading needs one complete online visit first.</p>';throw Error('Curriculum loading failed');}
let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw Error('Storage unavailable');},setItem(){throw Error('Storage unavailable');}};}
const loaded=read(storage,bank);let state=loaded.state,blocked=loaded.blocked,raw=loaded.raw,reason=loaded.reason||'',temporary=false,saveFailed=false,resetPending=false;
let cardRevealed=false,lastCard='',caseSolution=false,lastCase='',hintVisible=false,previousRoute='',labTab='waterfall';
const byQ=new Map(bank.questions.map(q=>[q.id,q]));const byM=new Map(bank.modules.map(m=>[m.id,m]));
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,cls='secondary',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const link=(label,url,cls='button secondary')=>`<a class="${cls}" href="${url}">${label}</a>`;
const title=(eyebrow,heading,desc)=>`<div class="page-title"><div class="eyebrow">${eyebrow}</div><h1>${heading}</h1><p class="muted">${desc}</p></div>`;
function persist(){
 if(blocked||temporary)return false;
 try{if(storage.getItem(KEY)!==raw){blocked=true;reason='Another tab changed saved progress. Reload to use its latest copy, or export this in-memory copy before choosing a temporary session.';renderNotice();return false;}}catch{blocked=true;reason='Browser storage is unavailable. Export current progress or choose a temporary session.';renderNotice();return false;}
 if(state.session)state.session.lastObserved=Math.max(state.session.lastObserved,Date.now());
 const result=save(storage,state);if(result.ok){raw=JSON.stringify(state);return true;}blocked=true;saveFailed=true;reason=result.reason;renderNotice();return false;
}
function download(value,name){const url=URL.createObjectURL(new Blob([value],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderNotice(){
 notice.innerHTML=blocked?`<div class="notice dangerbox" role="alert"><strong>Saved progress is protected</strong><p>${e(reason)} No saved bytes will be overwritten automatically.</p><div class="actions">${raw!==null?btn('Download saved bytes','export-raw'):''}${btn('Export current in-memory progress','export')}${btn('Continue temporarily','temporary')}${btn('Reload saved copy','reload')}${btn('Review reset options','reset','danger')}</div>${resetPending?resetPanel():''}</div>`:temporary?'<div class="notice"><strong>Temporary session</strong><p>Progress is kept only in this tab. Export it before leaving if you want to retain it.</p></div>':saveFailed?'<div class="notice" role="alert">Some recent progress may be unsaved. Export it before leaving.</div>':'';
}
function resetPanel(){return `<div class="panel"><h3>Reset saved progress deliberately</h3><p>Reset clears saved study and assessment state. The existing saved bytes will first be kept under a dated backup key in this browser. Download them for a portable recovery copy.</p><div class="actions">${btn('Download saved bytes','export-raw')}${btn('Reset and keep browser backup','confirm-reset','danger')}${btn('Cancel reset','cancel-reset')}</div></div>`;}
function provenance(item){return `<div class="source">${item.scope?`<strong>Scope:</strong> ${e(item.scope)} · Rule checked ${e(item.checked)}<br>`:''}${item.sources.map(ref=>{const s=bank.sources.find(x=>x.id===ref.id);return s.url?`<a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.title)}</a>${ref.section?` §${e(ref.section)}`:''}`:`${e(s.title)}${ref.pages?` · pp ${ref.pages.join(', ')}`:''}`;}).join('<br>')}</div>`;}
function moduleOptions(selected='all'){return `<option value="all">All modules</option>${bank.modules.map(m=>`<option value="${m.id}" ${selected===m.id?'selected':''}>${e(m.title)}</option>`).join('')}`;}
function difficultyOptions(selected='all'){return ['all','Foundation','Applied','Advanced'].map(d=>`<option value="${d}" ${selected===d?'selected':''}>${d==='all'?'All levels':d}</option>`).join('');}
function route(){const [path,query='']=(location.hash.slice(1)||'home').split('?');const [view,id]=path.split('/');return {view,id,query:new URLSearchParams(query)};}
function goto(value){if(location.hash===`#${value}`)render();else location.hash=value;}
function markSeen(qid){const h=state.history[qid]||{seen:0,attempts:[]};state.history[qid]={...h,seen:Math.min(h.seen+1,100000)};persist();}
function renderHome(){
 const done=state.lessons.length;
 main.innerHTML=`<section class="hero"><div><div class="eyebrow">A professional learning workspace</div><h1>Follow the money.<br>Understand the system.</h1><p class="intro">Build depth in Indian loan management, accounting and co-lending. Learn the model, work the numbers, then test your reasoning.</p><div class="actions">${link(done?'Continue learning':'Start with foundations',`#lesson/${bank.modules[Math.min(done,11)].id}`,'button')}${link('Explore worked cases','#cases')}</div></div><div class="flow"><div class="eyebrow" style="color:#edbb83">One event. Five connected views.</div><h3>A borrower pays an EMI</h3>${[['01','Instruction','What was intended?'],['02','Cash','What reached the bank?'],['03','Schedule','Which dues cleared?'],['04','Accounting','Which balances moved?'],['05','Evidence','Can we explain it?']].map(x=>`<div class="flowrow"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</div></section><div class="stats"><div class="stat"><strong>12</strong><span>Sequenced learning modules</span></div><div class="stat"><strong>120</strong><span>Meaningful flashcards</span></div><div class="stat"><strong>${bank.questions.length}</strong><span>MCQs with every option explained</span></div><div class="stat"><strong>${bank.cases.length}</strong><span>Multi-step worked cases</span></div></div><section><div class="sectionhead"><div><div class="eyebrow">The learning path</div><h2>From contract to control</h2></div><p>${done}/12 lessons marked read · Explore in order or choose a topic</p></div><div class="grid">${bank.modules.map((m,i)=>`<article class="tile"><span class="number">${String(i+1).padStart(2,'0')} / ${i<4?'BUILD THE MODEL':i<8?'TRACE THE MONEY':'HANDLE COMPLEXITY'}</span>${btn(state.bookmarks.includes(m.id)?'Saved':'Save','bookmark','subtle',`data-id="${m.id}" aria-pressed="${state.bookmarks.includes(m.id)}" aria-label="${state.bookmarks.includes(m.id)?'Unsave':'Save'} ${e(m.title)}"`)}<h3>${e(m.title)}</h3><p>${e(m.subtitle)}</p><span class="badge ${state.lessons.includes(m.id)?'good':''}">${state.lessons.includes(m.id)?'Marked read':'10 cards · 10 topic questions'}</span><a href="#lesson/${m.id}">Read lesson <span aria-hidden="true">↗</span></a></article>`).join('')}</div></section><div class="source">Original hypothetical examples. Rule checked 4 Oct 2026; scoped current RBI questions cite successor directions. Held conduct topics are excluded from current-law scoring. <a href="#sources">Inspect provenance and corrections</a>.</div>`;
}
function renderLesson(id){const m=byM.get(id);if(!m)return missing();const i=bank.modules.indexOf(m);main.innerHTML=`<div class="lesson-title"><div class="eyebrow">Module ${String(i+1).padStart(2,'0')} / 12 · Teach before practice</div><h1>${e(m.title)}</h1><p class="muted">${e(m.subtitle)}</p></div><div class="twocol"><article class="prose">${m.lesson.map(p=>`<p>${e(p)}</p>`).join('')}<label class="checklist"><input type="checkbox" data-action="lesson-read" data-id="${id}" ${state.lessons.includes(id)?'checked':''}> <span>Mark this lesson as read</span></label><div class="actions">${link('Review its flashcards',`#cards?module=${id}`,'button')}${link('Practice this topic',`#practice?module=${id}`)}${i<11?link('Next lesson',`#lesson/${bank.modules[i+1].id}`):link('Explore the cases','#cases')}</div>${provenance({sources:[{id:'guide',pages:m.pages}]})}</article><aside class="aside"><h3>Before you begin</h3><p>${m.prerequisites.length?`Suggested prerequisite: <a href="#lesson/${m.prerequisites[0]}">${e(byM.get(m.prerequisites[0]).title)}</a>.`:'No prerequisites. Start by learning the vocabulary and the five views.'}</p><h3>Think as you read</h3><p>What changes in cash? What changes in principal, interest or liabilities? Which event and rule version explains the result?</p>${btn(state.bookmarks.includes(id)?'Remove bookmark':'Bookmark lesson','bookmark','secondary',`data-id="${id}" aria-pressed="${state.bookmarks.includes(id)}"`)}<p class="small">Reading a lesson is recorded separately from independent question attempts. No mastery score is inferred from opening a lesson.</p></aside></div>`;}
function filteredCards(){return bank.cards.filter(c=>(state.filters.module==='all'||c.module===state.filters.module)&&(state.filters.difficulty==='all'||c.difficulty===state.filters.difficulty)&&`${c.front} ${c.back} ${byM.get(c.module).title}`.toLowerCase().includes(state.filters.search.toLowerCase()));}
function renderCards(id,query){if(query.has('module')&&byM.has(query.get('module'))){state.filters.module=query.get('module');persist();history.replaceState(null,'',`#cards/${id||''}`);}main.innerHTML=title('Recall and explain','Flashcards','Reveal a concept, connect it to a lesson, and describe the cash and ledger effects in your own words.')+`<div class="filters"><div class="field wide"><label for="card-search">Search concepts</label><input id="card-search" type="search" maxlength="300" placeholder="Try suspense, principal, escrow…" value="${e(state.filters.search)}"></div><div class="field"><label for="card-module">Module</label><select id="card-module">${moduleOptions(state.filters.module)}</select></div><div class="field"><label for="card-difficulty">Level</label><select id="card-difficulty">${difficultyOptions(state.filters.difficulty)}</select></div></div><div id="cardbody"></div>`;renderCardBody(id);}
function renderCardBody(id){const cards=filteredCards();const box=document.querySelector('#cardbody');if(!cards.length){box.innerHTML='<div class="panel"><h2>No matching cards</h2><p>Try a broader search or another module.</p></div>';return;}const index=Math.max(0,cards.findIndex(c=>c.id===id));const c=cards[index];if(lastCard!==c.id){cardRevealed=false;lastCard=c.id;const old=state.cards[c.id]||{seen:0,revealed:0};state.cards[c.id]={...old,seen:Math.min(old.seen+1,100000)};persist();}history.replaceState(null,'',`#cards/${c.id}`);box.innerHTML=`<div class="card-count"><span>${index+1} / ${cards.length} matching cards</span><span>${e(byM.get(c.module).title)} · ${c.difficulty}</span></div><article class="flash"><div class="eyebrow">${cardRevealed?'Concept revealed':'Think it through'}</div><h2>${e(c.front)}</h2>${cardRevealed?`<div class="answer">${e(c.back)}</div>${provenance(c)}`:''}</article><div class="actions">${btn('Previous card','card-prev','secondary',`data-id="${cards[(index-1+cards.length)%cards.length].id}"`)}${btn(cardRevealed?'Hide explanation':'Reveal explanation','card-flip','',`data-id="${c.id}" aria-expanded="${cardRevealed}"`)}${btn('Next card','card-next','secondary',`data-id="${cards[(index+1)%cards.length].id}"`)}${link('Read its lesson',`#lesson/${c.module}`)}</div><p class="small muted">Keyboard: ← previous, → next, Space to reveal when focus is on the card area. Card views and reveals are review activity, not proof of independent recall.</p>`;}
function renderPractice(query){const selected=byM.has(query.get('module'))?query.get('module'):'all';const s=state.session;
 main.innerHTML=title('Review or assess','Practice with purpose','Untimed by default. Optional timers are local practice tools; you can explicitly pause them, and reopening preserves the saved deadline.')+`<div class="twocol"><div class="panel">${s&&s.status==='active'?`<div class="feedback"><strong>An assessment is in progress</strong><p>${s.ids.length} questions · ${s.mode==='untimed'?'Untimed':s.mode==='session'?'Session timer':'Per-question timer'} · ${s.paused?'Paused':'Running'}</p>${link('Resume saved assessment','#quiz','button')}</div>`:''}<form id="setup"><div class="setup"><div class="field"><label for="quiz-module">Scope</label><select id="quiz-module">${moduleOptions(selected)}</select></div><div class="field"><label for="quiz-difficulty">Difficulty</label><select id="quiz-difficulty">${difficultyOptions()}</select></div><div class="field"><label for="quiz-count">Question count</label><select id="quiz-count"><option>10</option><option>20</option><option>30</option><option>50</option><option value="${bank.questions.length}">All ${bank.questions.length}</option></select></div><div class="field"><label for="quiz-mode">Timing</label><select id="quiz-mode"><option value="untimed">Untimed practice</option><option value="session">Whole session</option><option value="question">Per question</option></select></div><div class="field" id="time-field" hidden><label for="quiz-time" id="time-label">Session minutes</label><input id="quiz-time" type="number" min="1" max="180" value="15" required><span class="small muted" id="time-help">The clock keeps running while you navigate away or close the app. Pause explicitly to stop it.</span></div></div><p class="small muted">Questions are shuffled from the selected pool; fewer than the requested count are used when the pool is smaller. Every option gets an explanation after submission.</p>${btn(s&&s.status==='active'?'Start new (ends current assessment)':'Start practice','start','',blocked?'disabled':'')}<div id="setup-error" role="alert"></div></form></div><aside class="aside"><h3>A useful assessment</h3><p>First attempts, helped attempts and repeats are recorded separately. Reviewing an answer or a case solution means later answers are no longer independent first attempts.</p><h3>Timer behavior</h3><p>Session expiry ends the assessment. Per-question expiry records that question as timed out and waits for you to continue. An unsubmitted selected answer is not counted as correct.</p><p>Pausing is explicit and visible. Reduced motion is respected. No timer is required for study.</p>${link('Review your progress','#progress')}</aside></div>`;
}
function startSession(ids,mode='untimed',budget=0){if(blocked)return;if(state.session&&state.session.status==='active'){state.session.status='abandoned';persist();}const now=Date.now();state.session={ids,index:0,mode,budget,remaining:budget,deadline:mode==='untimed'?null:now+budget,paused:false,status:'active',selected:null,helped:false,results:{},startedAt:now,lastObserved:now};hintVisible=false;markSeen(ids[0]);persist();goto('quiz');}
function record(q,choice,timeout=false){const s=state.session;if(s.results[q.id])return;const correct=!timeout&&choice===q.answer;const exposed=state.exposed.includes(q.id);const h=classifyAttempt(state.history,q.id,{helped:s.helped,exposed,correct,timeout});state.history[q.id]=h;const kind=h.attempts.at(-1).kind;s.results[q.id]={choice,correct,timeout,helped:s.helped||exposed,kind};if(!state.exposed.includes(q.id))state.exposed.push(q.id);persist();}
function expire(now=Date.now()){
 const s=state.session;if(!s||s.status!=='active'||s.mode==='untimed'||s.paused)return false;
 if(now+1000<s.lastObserved){s.status='expired';s.expiryReason='The device clock moved backwards. This assessment is ended to preserve its time budget.';persist();return true;}
 if(s.mode==='question'&&s.results[s.ids[s.index]])return false;
 if(clockRemaining(s,now)>0)return false;
 if(s.mode==='session'){for(const id of s.ids){if(!s.results[id]){if(id===s.ids[s.index])record(byQ.get(id),null,true);else s.results[id]={choice:null,correct:false,timeout:true,helped:false,kind:'unanswered'};}}s.status='expired';s.expiryReason='The session deadline was reached. Unsubmitted questions are recorded as timed out.';}
 else{record(byQ.get(s.ids[s.index]),null,true);if(s.index===s.ids.length-1){s.status='expired';s.expiryReason='The final question timed out.';}}
 s.remaining=0;persist();return true;
}
function timerText(s){const remaining=clockRemaining(s);if(remaining===null)return 'Untimed';const seconds=Math.ceil(remaining/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} ${s.paused?'paused':'remaining'}`;}
function renderQuiz(){const s=state.session;if(!s){goto('practice');return;}expire();if(s.status!=='active')return renderResults();const q=byQ.get(s.ids[s.index]),r=s.results[q.id],caseItem=q.case?bank.cases.find(c=>c.id===q.case):null;
 main.innerHTML=`<div class="narrow"><div class="eyebrow">${e(byM.get(q.module).title)} · ${q.difficulty}</div><div class="quizhead"><span>Question ${s.index+1} / ${s.ids.length}</span><div class="actions"><span class="timer" id="timer" role="timer" aria-label="${e(timerText(s))}">${timerText(s)}</span>${s.mode!=='untimed'&&!r?btn(s.paused?'Resume timer':'Pause timer',s.paused?'resume-timer':'pause-timer','secondary'):''}</div></div><div class="progressbar" aria-hidden="true"><span style="width:${s.index/s.ids.length*100}%"></span></div>${s.paused?'<div class="feedback"><strong>Timer paused</strong><p>Resume to submit an answer. The saved remaining budget stays unchanged while paused.</p></div>':''}${caseItem?`<div class="panel"><h3>${e(caseItem.title)}</h3><p>${e(caseItem.scenario)}</p></div>`:''}<form id="question-form" class="question"><fieldset ${s.paused?'disabled':''}><legend class="sr-only">${e(q.prompt)}</legend><h2>${e(q.prompt)}</h2>${q.options.map((o,i)=>`<label class="option ${r?(i===q.answer?'correct':i===r.choice?'incorrect':''):''}"><input type="radio" name="choice" value="${i}" ${s.selected===i?'checked':''} ${r||blocked?'disabled':''}><span>${e(o.text)}${r?`<span class="explanation"><strong>${i===q.answer?'Correct option.':i===r.choice?'Your choice.':'Other option.'}</strong> ${e(o.explanation)}</span>`:''}</span></label>`).join('')}</fieldset>${hintVisible&&!r?`<div class="hint"><strong>Reasoning help (marks attempt as helped)</strong><p>${e(bank.cards.find(c=>`q-${c.id}`===q.id)?.back||'Write the cash conservation equation, identify disjoint components, and use only the assumptions supplied in the case. No current rule can be inferred beyond its stated scope.')}</p></div>`:''}${r?`<div class="feedback" id="feedback" tabindex="-1"><strong>${r.timeout?'Time expired — no submitted answer':r.correct?'Correct reasoning':'Review the reasoning'}</strong><p>${r.kind==='independent-first'?'First independent attempt':r.kind==='helped'?'Helped first attempt':'Repeated attempt'} · ${r.timeout?'Recorded as timed out.':r.correct?'Correct answer recorded.':'Incorrect answer recorded.'}</p></div><div class="actions">${btn(s.index===s.ids.length-1?'View results':'Next question','next-question','',blocked?'disabled':'')}${link('Read this lesson',`#lesson/${q.module}`)}</div>`:`<div class="actions">${btn('Check answer','submit-answer','',s.selected===null||s.paused||blocked?'disabled':'')}${btn('Show reasoning help','hint','secondary',s.paused||blocked?'disabled':'')}</div>`}</form>${provenance(q)}<div class="source">${btn('End assessment and review','end-session','subtle',blocked?'disabled':'')} ${link('Leave view (clock continues unless paused)','#practice','small')}</div><div id="timer-alert" class="sr-only" aria-live="polite"></div></div>`;
}
function renderResults(){const s=state.session,results=Object.values(s.results),correct=results.filter(r=>r.correct).length,timeout=results.filter(r=>r.timeout).length;main.innerHTML=`<div class="narrow">${title('Assessment review',s.status==='expired'?'Time budget reached':s.status==='abandoned'?'Assessment ended':'Practice complete',s.expiryReason||'Use the explanations to identify the next concept to study. This result is practice evidence, not a certification.')}<div class="stats"><div class="stat"><strong>${correct}/${s.ids.length}</strong><span>Correct submitted answers</span></div><div class="stat"><strong>${results.filter(r=>r.kind==='independent-first').length}</strong><span>Independent first attempts</span></div><div class="stat"><strong>${results.filter(r=>r.kind==='helped').length}</strong><span>Helped first attempts</span></div><div class="stat"><strong>${timeout}</strong><span>Timed-out questions</span></div></div><p class="muted">${results.filter(r=>r.kind==='repeat').length} repeated attempts · ${s.ids.length-results.length+results.filter(r=>r.kind==='unanswered').length} unanswered · ${s.mode==='untimed'?'Untimed':s.mode==='session'?'Whole-session timer':'Per-question timer'}. Scores include repeats and help; first independent performance is reported separately in Progress. No pass or mastery claim is inferred.</p><div class="actions">${link('Return to practice','#practice','button')}${btn('Review same questions untimed','review-session','secondary',blocked?'disabled':'')}${link('See learning progress','#progress')}</div>${s.ids.map(id=>{const q=byQ.get(id),r=s.results[id];return `<details><summary>${e(q.prompt)} — ${r?r.timeout?'Timed out':r.correct?'Correct':'Incorrect':'Unanswered'}</summary>${q.options.map((o,i)=>`<p><strong>${i===q.answer?'Correct: ':''}${e(o.text)}</strong><br>${e(o.explanation)}</p>`).join('')}${provenance(q)}</details>`;}).join('')}</div>`;for(const id of s.ids)if(!state.exposed.includes(id))state.exposed.push(id);persist();}
function renderCases(){main.innerHTML=title('Transfer your knowledge','Worked cases','Fifteen multi-step scenarios connect cash, schedules, component balances and control evidence. Study the solution, then practice its decisions.')+`<div class="grid">${bank.cases.map((c,i)=>`<article class="tile"><div class="number">CASE ${String(i+1).padStart(2,'0')} · ADVANCED</div><h3>${e(c.title)}</h3><p>${e(c.scenario)}</p><span class="badge">${c.questions.length} case questions · ${c.steps.length} worked steps</span><a href="#case/${c.id}">Work through this case ↗</a></article>`).join('')}</div>`;}
function renderCase(id){const c=bank.cases.find(c=>c.id===id);if(!c)return missing();if(lastCase!==id){caseSolution=false;lastCase=id;}main.innerHTML=`<div class="narrow">${title('Advanced integrated case',e(c.title),e(byM.get(c.module).title))}<div class="panel"><h2>Scenario and assumptions</h2><p>${e(c.scenario)}</p></div><p class="muted">Before revealing the solution, write the money-conservation equation and identify which balances change.</p><div class="actions">${btn(caseSolution?'Hide worked solution':'Reveal worked solution','case-solution','',`data-id="${id}" aria-expanded="${caseSolution}"`)}${btn('Practice this case','case-practice','secondary',`data-id="${id}" ${blocked?'disabled':''}`)}${link('Read the supporting lesson',`#lesson/${c.module}`)}</div>${caseSolution?`<section style="margin-top:2rem"><h2>Worked solution</h2>${c.steps.map((s,i)=>`<div class="case-step"><span>${i+1}</span><p>${e(s)}</p></div>`).join('')}<p class="small muted">Opening this solution marks its questions as exposed. Later attempts remain useful review, and are recorded separately from independent first attempts.</p></section>`:''}${provenance(c)}</div>`;}
function renderSources(){main.innerHTML=title('Provenance and limits','Read the rule, check the scope','Rule checked 4 Oct 2026. Teaching examples state assumptions; current graded statutory questions map to verified sections of primary RBI successors.')+`<div class="panel"><h2>How to read this learning bank</h2><p>The user-supplied handbook is educational material, dated 27 June 2026, with OpenAI author metadata. It is not official authority or an empirical study. This app paraphrases concepts and supplies original hypothetical cases; the original PDF is preserved and is not published.</p><p>Accounting examples use stated simplified ledger assumptions. Actual recognition, EIR/ECL, tax, NPA and capital treatment require the applicable entity and accounting regime. Contract allocation does not automatically determine revenue recognition.</p><p><strong>Held out of current-law scoring:</strong> current prepayment/KFS/penal-charge successor details; current bank digital-specific rules; cross-regime numerical DLG mechanics; universal impairment and income-recognition assertions.</p></div><h2 style="margin-top:2rem">Corrections to the supplied guide</h2>${bank.corrections.map(c=>`<p>${e(c)}</p>`).join('')}<h2 style="margin-top:2rem">Source register</h2>${bank.sources.map(s=>`<article class="sourceblock"><span class="badge">${e(s.kind)}</span><h3>${s.url?`<a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.title)}</a>`:e(s.title)}</h3><p><strong>${e(s.date)}</strong><br>${e(s.note)}</p>${s.hash?`<details><summary>Source fingerprint</summary><p style="overflow-wrap:anywhere">SHA-256: ${s.hash}</p></details>`:''}</article>`).join('')}`;}
function renderProgress(){const histories=Object.values(state.history),first=histories.filter(h=>h.first?.kind==='independent-first'),correct=first.filter(h=>h.first.correct).length,helped=histories.filter(h=>h.first?.kind==='helped').length,repeats=histories.reduce((n,h)=>n+h.attempts.filter(a=>a.kind==='repeat').length,0);const seen=histories.filter(h=>h.seen).length;main.innerHTML=title('Your learning record','Progress, with context','Stored only in this browser. Views, reviewed solutions, helped answers and independent first attempts are different evidence.')+`<div class="stats"><div class="stat"><strong>${state.lessons.length}/12</strong><span>Lessons marked read</span></div><div class="stat"><strong>${correct}/${first.length}</strong><span>Correct on independent first attempt</span></div><div class="stat"><strong>${helped}</strong><span>Helped first attempts</span></div><div class="stat"><strong>${repeats}</strong><span>Repeated attempts</span></div></div><p class="muted">${seen} distinct questions seen · ${Object.values(state.cards).filter(c=>c.seen).length} cards viewed · ${Object.values(state.cards).filter(c=>c.revealed).length} cards revealed · ${state.exposed.length} question solutions or related answer help exposed. No mastery percentage is inferred from these counts.</p><div class="twocol"><div class="panel"><h2>By module</h2><div class="tablewrap"><table><thead><tr><th scope="col">Module</th><th scope="col">Independent first correct / tried</th><th scope="col">Lesson read</th></tr></thead><tbody>${bank.modules.map(m=>{const qs=bank.questions.filter(q=>q.module===m.id),hs=qs.map(q=>state.history[q.id]?.first).filter(x=>x?.kind==='independent-first');return `<tr><td><a href="#lesson/${m.id}">${e(m.title)}</a></td><td>${hs.filter(x=>x.correct).length} / ${hs.length}</td><td>${state.lessons.includes(m.id)?'Yes':'—'}</td></tr>`;}).join('')}</tbody><caption>Independent first means the first submitted or expired attempt without in-app solution exposure or reasoning help. Prior study is encouraged. Local editable data is not certification evidence.</caption></table></div></div><aside class="aside"><h3>Saved lessons</h3>${state.bookmarks.length?state.bookmarks.map(id=>`<p><a href="#lesson/${id}">${e(byM.get(id).title)}</a></p>`).join(''):'<p>Use Save on a curriculum module to bookmark it.</p>'}<h3>Keep a portable copy</h3><div class="actions">${btn('Export progress','export')}${btn('Review reset options','reset','danger')}</div><div class="field" style="margin-top:1rem"><label for="import-file">Import a valid progress file</label><input id="import-file" type="file" accept=".json,application/json" ${blocked?'disabled':''}></div><p class="small">Import is reviewed before replacement, and the old saved bytes are backed up. Unknown or future versions are protected.</p><div id="import-result" role="status"></div></aside></div>${resetPending?resetPanel():''}`;}
function missing(){main.innerHTML=title('Route not found','Choose a learning page','The link does not match a module, card or case in this version.')+link('Open curriculum','#home','button');}
function render(){const r=route(),changed=location.hash!==previousRoute;previousRoute=location.hash;document.querySelectorAll('nav a').forEach(a=>{const v=a.hash.slice(1);const active=v===r.view||(v==='home'&&r.view==='lesson')||(v==='practice'&&r.view==='quiz')||(v==='cases'&&r.view==='case');if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.body.classList.toggle('large',state.settings.large);document.querySelector('#large').setAttribute('aria-pressed',state.settings.large);renderNotice();({home:renderHome,lesson:()=>renderLesson(r.id),cards:()=>renderCards(r.id,r.query),practice:()=>renderPractice(r.query),quiz:renderQuiz,cases:renderCases,case:()=>renderCase(r.id),lab:renderLab,sources:renderSources,progress:renderProgress}[r.view]||missing)();document.title=`${main.querySelector('h1')?.textContent||'Assessment'} · Lending Systems Lab`;if(changed){main.focus({preventScroll:true});window.scrollTo(0,0);}}
function table(headers,rows,caption){return `<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody><caption>${caption}</caption></table></div>`;}
function renderLab(){main.innerHTML=title('Observe cause and effect','Cashflow reasoning lab','Change the assumptions, compare outcomes and inspect the ledger. All models here are illustrative policies, with amounts rounded to paise.')+`<div class="actions">${[['waterfall','Allocation & ledger'],['shares','Co-lending shares'],['yield','EMI & EIR']].map(([id,label])=>btn(label,'lab-tab',labTab===id?'':'secondary',`data-id="${id}" aria-pressed="${labTab===id}"`)).join('')}</div><div id="lab-body" style="margin-top:1.5rem"></div>`;renderLabBody();}
function renderLabBody(){const body=document.querySelector('#lab-body');if(labTab==='waterfall'){body.innerHTML=`<div class="labgrid"><section class="panel"><h2>One payment, two policies</h2><p>A: charge ₹100, interest ₹900, principal ₹3,000.<br>B: charge ₹100, interest ₹800, principal ₹3,000.</p><div class="field"><label for="lab-payment">Verified receipt (₹0–₹20,000)</label><input id="lab-payment" type="number" min="0" max="20000" step="0.01" value="4000"></div><div class="field" style="margin-top:1rem"><label for="lab-order">Waterfall policy</label><select id="lab-order"><option value="vertical">Vertical: bucket first</option><option value="horizontal">Horizontal: component first</option></select></div><p class="small muted">Charge → interest → principal; oldest-first within each selected component. No tax, grace period or impairment. DPD considers unpaid principal/interest.</p></section><section class="panel" id="allocation-output" aria-live="polite"></section></div><section class="panel" style="margin-top:1.5rem"><h2>Trace the journal: cash once</h2><div id="journal-output"></div><p class="small muted">Assumed lender accrual ledger with existing charge/interest receivables and inclusive POS. Receipt is bank→clearing; allocation is clearing→components. An allocation-only reversal restores due components without moving cash. A refund/chargeback requires a separate cash event.</p></section>`;updateAllocation();}
 else if(labTab==='shares'){body.innerHTML=`<div class="labgrid"><section class="panel"><h2>Entitlement before payout</h2><p>₹1,00,000 opening borrower POS. Monthly rates use annual/12. The receipt's principal and interest are allocated before share splitting.</p><div class="setup"><div class="field"><label for="share-a">A principal funding (%)</label><input id="share-a" type="number" min="10" max="90" value="80"></div><div class="field"><label for="rate-a">A nominal annual rate (%)</label><input id="rate-a" type="number" min="0" max="50" step="0.1" value="10.5"></div><div class="field"><label for="rate-b">B nominal annual rate (%)</label><input id="rate-b" type="number" min="0" max="50" step="0.1" value="18"></div><div class="field"><label for="share-principal">Principal payment (₹)</label><input id="share-principal" type="number" min="0" max="100000" step="0.01" value="4000"></div></div><p class="small muted">Principal follows the selected ratio. Interest is computed from each share balance and its rate. A gets rounded paise; B gets residual principal. No fee/servicing commercial arrangements or DLG assumed.</p></section><section class="panel" id="share-output" aria-live="polite"></section></div>`;updateShares();}
 else{body.innerHTML=`<div class="panel"><h2>Contractual schedule and fee-adjusted carrying value</h2><p>Performing asset, monthly equal periods, all payments on time. Explicit policy: qualifying origination fee withheld and deferred through EIR; no impairment, tax, transaction costs or modifications. No universal fee accounting or statutory APR treatment is implied.</p><div class="setup"><div class="field"><label for="yield-principal">Contract principal (₹)</label><input id="yield-principal" type="number" min="1000" max="10000000" step="100" value="120000"></div><div class="field"><label for="yield-rate">Nominal annual rate (%)</label><input id="yield-rate" type="number" min="0" max="36" step="0.1" value="12"></div><div class="field"><label for="yield-months">Monthly payment count</label><input id="yield-months" type="number" min="1" max="120" value="12"></div><div class="field"><label for="yield-fee">Qualifying withheld fee (₹)</label><input id="yield-fee" type="number" min="0" max="999999" step="0.01" value="2400"></div></div><p class="small muted">Round regular EMI and each nominal interest to paise; final cash = remaining principal + rounded nominal interest. Solve EIR against those actual expected cash amounts. Round EIR income monthly; final income clears the carrying residual.</p></div><div id="yield-output" aria-live="polite"></div>`;updateYield();}}
function validNum(id,min,max,integer=false){const field=document.getElementById(id),n=Number(field.value);if(field.value===''||!Number.isFinite(n)||n<min||n>max||integer&&!Number.isInteger(n))return null;return n;}
function updateAllocation(){const payment=validNum('lab-payment',0,20000),output=document.querySelector('#allocation-output');if(payment===null){output.innerHTML='<h3>Enter a valid receipt amount</h3><p>Use a finite amount between ₹0 and ₹20,000.</p>';document.querySelector('#journal-output').innerHTML='';return;}const result=allocate(round(payment),[{charge:100,interest:900,principal:3000},{charge:100,interest:800,principal:3000}],document.querySelector('#lab-order').value);output.innerHTML=`<h2>Allocation result</h2><div class="metric">${money(result.applied)} applied</div><p>${money(result.unapplied)} remains unapplied.<br>Oldest relevant unpaid bucket: ${result.remaining.findIndex(b=>b.interest+b.principal>0)===-1?'None':['A','B'][result.remaining.findIndex(b=>b.interest+b.principal>0)]}</p>${table(['Line','Component','Applied'],result.lines.map(l=>[[ 'A','B'][l.bucket-1],l.component,money(l.amount)]),'Allocation lines conserve the receipt.')}${table(['Bucket','Charge left','Interest left','Principal left'],result.remaining.map((b,i)=>[['A','B'][i],money(b.charge),money(b.interest),money(b.principal)]),'Remaining due totals change by allocated cash only.')}`;const totals={charge:0,interest:0,principal:0};result.lines.forEach(l=>totals[l.component]=round(totals[l.component]+l.amount));document.querySelector('#journal-output').innerHTML=table(['Stage','Debit','Credit'],[['Receipt',`Bank ${money(round(payment))}`,`Payment clearing ${money(round(payment))}`],['Allocation',`Payment clearing ${money(round(payment))}`,`Charge receivable ${money(totals.charge)}<br>Interest receivable ${money(totals.interest)}<br>Principal ${money(totals.principal)}<br>Unapplied liability ${money(result.unapplied)}`]],'Total debit equals total credit at each stage. Allocation adds zero new cash.');}
function updateShares(){const share=validNum('share-a',10,90),ra=validNum('rate-a',0,50),rb=validNum('rate-b',0,50),p=validNum('share-principal',0,100000),out=document.querySelector('#share-output');if([share,ra,rb,p].some(n=>n===null)){out.innerHTML='<h3>Check the share inputs</h3><p>Use the stated ranges; all values must be finite.</p>';return;}const totalInterest=round(100000*(share/100*ra+(1-share/100)*rb)/1200),s=split(round(p),totalInterest,100000,share/100,ra,rb);out.innerHTML=`<h2>Different ratios, same receipt</h2><p>Blended nominal rate <strong>${s.blended.toFixed(2)}%</strong><br>Monthly borrower interest <strong>${money(totalInterest)}</strong></p>${table(['Component','A entitlement','B entitlement'],[['Principal',money(s.principalA),money(s.principalB)],['Interest',money(s.interestA),money(s.interestB)],['Total cash',money(s.totalA),money(s.totalB)]],'Each row sums to the borrower component. Different share rates change the interest ratio.')}<p>A naive ${share}:${100-share} split of total receipt would give A ${money(round((p+totalInterest)*share/100))}. The correct entitlement under these assumptions is ${money(s.totalA)}.</p><div class="feedback">Principal is funding-share proportional. Interest is rate-weighted. Escrow cash and confirmed payouts must reconcile to these entitlements.</div>`;}
async function updateYield(){const out=document.querySelector('#yield-output'),p=validNum('yield-principal',1000,10000000),rate=validNum('yield-rate',0,36),n=validNum('yield-months',1,120,true),fee=validNum('yield-fee',0,999999);if([p,rate,n,fee].some(x=>x===null)||fee>=p){out.innerHTML='<div class="feedback">Enter valid values within the ranges. The qualifying fee must be less than principal.</div>';return;}const {eirSchedule}=await import('./engine.mjs');let data;try{data=eirSchedule(round(p),rate,n,round(fee));}catch{out.innerHTML='<div class="feedback">These cashflows do not support the stated model. Adjust the inputs.</div>';return;}out.innerHTML=`<section class="panel" style="margin-top:1.5rem"><div class="stats"><div class="stat"><strong>${money(data.rows[0].payment)}</strong><span>First contractual payment</span></div><div class="stat"><strong>${(data.yieldRate*100).toFixed(4)}%</strong><span>Monthly EIR</span></div><div class="stat"><strong>${(data.effectiveAnnual*100).toFixed(4)}%</strong><span>Effective annual EIR</span></div><div class="stat"><strong>${money(p-fee)}</strong><span>Initial net carrying</span></div></div>${table(['Month','Gross open','Nominal interest','Cash payment','Gross close'],data.rows.map(r=>[r.month,money(r.opening),money(r.interest),money(r.payment),money(r.closing)]),'Contractual gross principal schedule. All payments assumed successful; a bounced installment would not reduce actual POS.')}${table(['Month','Carrying open','EIR income','Fee accretion','Carrying close','Deferred fee'],data.rows.map(r=>[r.month,money(r.carryingOpen),money(r.income),money(r.feeAccretion),money(r.carryingClose),money(r.deferred)]),'Assumed qualifying-fee EIR schedule. Gross close minus deferred fee equals carrying close. Final income absorbs the paise residual.')}<p>Month 1 journal bridge: nominal interest income ${money(data.rows[0].interest)} + qualifying fee accretion ${money(data.rows[0].feeAccretion)} = EIR income ${money(data.rows[0].income)}. Receipt principal reduces gross exposure; fee accretion reduces the contra-asset.</p><p class="small muted">EIR is not a statutory APR certificate. Dated irregular cashflows require an actual-date yield model; this calculator uses equal monthly periods only.</p></section>`;}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[out[i],out[j]]=[out[j],out[i]];}return out;}
let importCandidate=null;
document.addEventListener('click',event=>{
 const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const action=target.dataset.action,id=target.dataset.id;
 if(action==='bookmark'){state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];persist();render();}
 if(action==='card-prev'||action==='card-next'){cardRevealed=false;goto(`cards/${id}`);}
 if(action==='card-flip'){cardRevealed=!cardRevealed;if(cardRevealed){state.cards[id].revealed=Math.min(state.cards[id].revealed+1,100000);if(!state.exposed.includes(`q-${id}`))state.exposed.push(`q-${id}`);persist();}renderCardBody(id);}
 if(action==='start'){const scope=document.querySelector('#quiz-module').value,level=document.querySelector('#quiz-difficulty').value,count=Number(document.querySelector('#quiz-count').value),mode=document.querySelector('#quiz-mode').value;const field=document.querySelector('#quiz-time');const time=Number(field.value),max=mode==='session'?180:600,min=mode==='session'?1:15;if(mode!=='untimed'&&(!field.value||!Number.isFinite(time)||time<min||time>max)){document.querySelector('#setup-error').textContent=`Choose ${min}–${max} ${mode==='session'?'minutes':'seconds'}.`;return;}const pool=bank.questions.filter(q=>(scope==='all'||q.module===scope)&&(level==='all'||q.difficulty===level));if(!pool.length){document.querySelector('#setup-error').textContent='No questions match this scope and difficulty.';return;}startSession(shuffle(pool).slice(0,count).map(q=>q.id),mode,mode==='untimed'?0:time*(mode==='session'?60000:1000));}
 if(action==='submit-answer'){if(blocked||expire()){renderQuiz();return;}const s=state.session;if(!s||s.paused||s.selected===null)return;record(byQ.get(s.ids[s.index]),s.selected);renderQuiz();document.querySelector('#feedback')?.focus();}
 if(action==='hint'){state.session.helped=true;hintVisible=true;persist();renderQuiz();}
 if(action==='next-question'){const s=state.session;if(s.index===s.ids.length-1){s.status='complete';persist();renderQuiz();return;}if(expire()&&s.status!=='active'){renderQuiz();return;}s.index++;s.selected=null;s.helped=false;hintVisible=false;if(s.mode==='question'){s.remaining=s.budget;s.deadline=Date.now()+s.budget;s.paused=false;}markSeen(s.ids[s.index]);persist();renderQuiz();main.focus();}
 if(action==='pause-timer'){if(expire()){renderQuiz();return;}state.session=pauseClock(state.session);persist();renderQuiz();}
 if(action==='resume-timer'){state.session=resumeClock(state.session);persist();renderQuiz();}
 if(action==='end-session'){state.session.status='abandoned';persist();renderQuiz();}
 if(action==='review-session'){startSession([...state.session.ids]);}
 if(action==='case-solution'){caseSolution=!caseSolution;if(caseSolution){const c=bank.cases.find(c=>c.id===id);state.exposed=[...new Set([...state.exposed,...c.questions])];persist();}renderCase(id);}
 if(action==='case-practice'){startSession(bank.cases.find(c=>c.id===id).questions);}
 if(action==='lab-tab'){labTab=id;renderLab();}
 if(action==='export')download(JSON.stringify(state,null,2),'lending-lab-progress.json');
 if(action==='export-raw'&&raw!==null)download(raw,'lending-lab-saved-bytes.json');
 if(action==='temporary'){temporary=true;blocked=false;resetPending=false;render();}
 if(action==='reload')location.reload();
 if(action==='reset'){resetPending=true;render();}
 if(action==='cancel-reset'){resetPending=false;render();}
 if(action==='confirm-reset'){const result=recoverReset(storage,raw);if(result.ok){state=result.state;raw=JSON.stringify(state);blocked=false;temporary=false;saveFailed=false;resetPending=false;lastCard='';goto('home');render();}else{reason=result.reason;blocked=true;renderNotice();}}
 if(action==='confirm-import'&&importCandidate){try{if(storage.getItem(KEY)!==raw)throw Error('Another tab changed saved progress. Reload before importing.');if(raw!==null)storage.setItem(`${KEY}:backup:${Date.now()}`,raw);const result=save(storage,importCandidate);if(!result.ok)throw Error(result.reason);state=importCandidate;raw=JSON.stringify(state);importCandidate=null;lastCard='';render();}catch(error){document.querySelector('#import-result').textContent=error.message;}}
 if(action==='cancel-import'){importCandidate=null;document.querySelector('#import-result').textContent='Import cancelled. Saved progress was retained.';}
});
document.addEventListener('change',async event=>{const t=event.target;if(t.dataset.action==='lesson-read'){state.lessons=t.checked?[...new Set([...state.lessons,t.dataset.id])]:state.lessons.filter(id=>id!==t.dataset.id);persist();}if(t.id==='card-module'||t.id==='card-difficulty'){state.filters[t.id==='card-module'?'module':'difficulty']=t.value;persist();lastCard='';renderCardBody();}if(t.name==='choice'&&state.session){state.session.selected=Number(t.value);persist();document.querySelector('[data-action="submit-answer"]')?.removeAttribute('disabled');}if(t.id==='quiz-mode'){const timed=t.value!=='untimed';document.querySelector('#time-field').hidden=!timed;const question=t.value==='question';document.querySelector('#time-label').textContent=question?'Seconds per question':'Session minutes';const input=document.querySelector('#quiz-time');input.min=question?'15':'1';input.max=question?'600':'180';input.value=question?'90':'15';}if(t.id==='lab-order')updateAllocation();if(t.id==='import-file'){const file=t.files[0];const box=document.querySelector('#import-result');if(!file)return;if(file.size>1048576){box.textContent='File is too large. No saved bytes changed.';return;}const text=await file.text();const result=validate(text,bank);if(!result.ok){box.textContent=`Import rejected: ${result.reason} No saved bytes changed.`;return;}importCandidate=result.data;box.innerHTML=`<p>Valid file: ${result.data.lessons.length} read lessons and ${Object.keys(result.data.history).length} question histories. Replace current saved progress and keep a dated browser backup?</p>${btn('Replace with imported progress','confirm-import')}${btn('Cancel','cancel-import')}`;}});
document.addEventListener('input',event=>{const t=event.target;if(t.id==='card-search'){state.filters.search=t.value;persist();lastCard='';renderCardBody();}if(t.id==='lab-payment')updateAllocation();if(['share-a','rate-a','rate-b','share-principal'].includes(t.id))updateShares();if(t.id.startsWith('yield-'))updateYield();});
document.querySelector('#large').addEventListener('click',()=>{state.settings.large=!state.settings.large;persist();document.body.classList.toggle('large',state.settings.large);document.querySelector('#large').setAttribute('aria-pressed',state.settings.large);});
document.addEventListener('keydown',event=>{if(route().view!=='cards'||/INPUT|SELECT|TEXTAREA|BUTTON|A/.test(event.target.tagName))return;const actions={ArrowLeft:'card-prev',ArrowRight:'card-next',' ':'card-flip'};if(actions[event.key]){event.preventDefault();document.querySelector(`[data-action="${actions[event.key]}"]`)?.click();}});
window.addEventListener('hashchange',()=>{persist();render();});
window.addEventListener('pagehide',()=>{expire();persist();});
document.addEventListener('visibilitychange',()=>{expire();persist();if(!document.hidden&&route().view==='quiz')renderQuiz();});
window.addEventListener('storage',event=>{if(event.key===KEY&&event.newValue!==raw&&!temporary){blocked=true;reason='Another tab updated saved progress. This tab is protected from overwriting it. Reload the saved copy or export and continue temporarily.';renderNotice();}});
setInterval(()=>{if(expire()){if(route().view==='quiz')renderQuiz();else{const s=state.session;notice.innerHTML=`<div class="notice" role="status"><strong>${s.status==='expired'?'Assessment time reached':'Question time reached'}</strong><p>The saved assessment records expiry. <a href="#quiz">Open it to review or continue</a>.</p></div>`;}return;}const s=state.session;if(s){const node=document.querySelector('#timer');if(node){node.textContent=timerText(s);node.setAttribute('aria-label',timerText(s));node.classList.toggle('warn',clockRemaining(s)!==null&&clockRemaining(s)<=30000);}}},250);
render();
fetch(new URL('../revision.json',import.meta.url)).then(r=>r.json()).then(r=>document.querySelector('#revision').textContent=`Revision ${r.sha.slice(0,8)}`).catch(()=>{});
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register(new URL('../sw.js',import.meta.url)).then(async registration=>{await navigator.serviceWorker.ready;document.querySelector('#offline').textContent=navigator.serviceWorker.controller?'Offline available • Local-only progress':'Preparing offline copy…';registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed')document.querySelector('#offline').textContent=navigator.serviceWorker.controller?'Update ready on next visit':'Offline copy prepared for next visit';});});}).catch(()=>document.querySelector('#offline').textContent='Online mode • Local-only progress');
